[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
headcount = "9NeaXRkbU4Jxsmh2aJyN74gxRoAR7fYupV68FEzDH6KH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx ../tests/program.test.ts"
